services:
  app:
    build: ./app
    volumes:
      - static_data:/app/static
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    depends_on:
      - app
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt
      - static_data:/app/static
      - letsencrypt_data:/etc/letsencrypt
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # certbot:
    # image: certbot/certbot
    # ports:
    #   - "80:80"
    # network_mode: hos–µ
    # volumes:
      # - letsencrypt_data:/etc/letsencrypt

volumes:
  static_data:
  postgres_data:
  letsencrypt_data:
