services:
  app:
    build: ./app
    volumes:
      - static_data:/app/static
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - static_data:/app/static
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  static_data:
  postgres_data:
