# run command below to obtain certificates before running docker compose to start the whole project:
# docker compose run --rm --service-ports certbot certonly --standalone -d there-is-a-bug.ru -d www.there-is-a-bug.ru
services:
  certbot:
    build: .
    ports:
      - "80:80"
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - webroot_data:/var/www/html

volumes:
  letsencrypt_data:
  webroot_data: 
