# Generated by Django 4.0.5 on 2022-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(default='1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_url', models.URLField()),
                ('salt', models.CharField(max_length=32)),
                ('pass_to_delete', models.IntegerField(default='', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
