# Generated by Django 4.0.5 on 2022-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0003_alter_salt_salt_alter_url_pass_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='salt',
            field=models.IntegerField(),
        ),
    ]
