# Generated by Django 4.0.5 on 2022-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0004_alter_url_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='pass_to_delete',
        ),
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
