# Generated by Django 4.0.5 on 2022-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0005_remove_url_pass_to_delete_url_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salt',
        ),
        migrations.AlterField(
            model_name='url',
            name='salt',
            field=models.IntegerField(default=0),
        ),
    ]
