# Generated by Django 4.0.5 on 2022-06-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0006_delete_salt_alter_url_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='salt',
            new_name='clck',
        ),
    ]
