# Generated by Django 4.0.5 on 2022-06-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0008_rename_clck_url_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='long_url',
        ),
    ]
