# Generated by Django 3.2 on 2022-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0010_rename_click_url_clicks_url_clicks_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
