# Generated by Django 3.2 on 2022-07-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0012_url_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user_ip',
        ),
    ]
