# Generated by Django 3.2 on 2022-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0015_alter_url_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='user_ip',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
    ]
