# Generated by Django 3.2.14 on 2022-08-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0017_rename_short_url_url_short_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_hash',
            field=models.CharField(max_length=50),
        ),
    ]
