# Generated by Django 3.2.14 on 2022-08-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0022_alter_url_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=2048)),
            ],
        ),
    ]
