# Generated by Django 3.2.14 on 2023-01-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0024_forbiddendomain_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user_ip',
        ),
    ]
