# Generated by Django 3.2.14 on 2023-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0025_remove_url_user_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='clicks',
            new_name='clicks_on_long_url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='clicks_per_day',
        ),
        migrations.AddField(
            model_name='url',
            name='clicks_on_short_url',
            field=models.IntegerField(default=0),
        ),
    ]
