# Generated by Django 3.2.14 on 2023-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0026_auto_20230222_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_lazy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
