# Generated by Django 3.2.14 on 2023-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0027_url_is_lazy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forbiddendomain',
            name='domain',
            field=models.URLField(max_length=2048),
        ),
    ]
