# Generated by Django 5.0.1 on 2024-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0031_alter_url_forbidden_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_redirected',
            field=models.BooleanField(default=False),
        ),
    ]
