from django.contrib.auth.hashers import check_password
from django.core.validators import ValidationError
from django.db.models import F
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import RedirectView, TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from short_urls.forms import UrlCreateForm
from short_urls.models import Url
from short_urls.services import create_url_object
from short_urls.validators import LzyURLValidator


class UrlCreate(View):
    """
    Create short url when user has typed command in browser's address bar
    """
    validate_url = LzyURLValidator()

    def get(self, request, **kwargs):
        long_url = kwargs.get('url', '')
        try:
            self.validate_url(long_url)
            url_obj, raw_password = create_url_object(long_url, is_lazy=True)

            # prepare dict to pass to UrlCreateSuccess view for context data
            request.session.update({
                'short_url_hash': url_obj.short_url_hash,
                'raw_password': raw_password
            })
            return redirect('url-create-success')
        except ValidationError as e:
            return render(
                request, 'short_urls/url_create_error.html', context={'error': e.message}
            )


class UrlCreateByForm(FormView):
    form_class = UrlCreateForm
    success_url = reverse_lazy('url-create-success')
    template_name = 'short_urls/url_create_success.html'

    def form_valid(self, form):
            long_url = form.cleaned_data.get('long_url')
            url_obj, raw_password = create_url_object(long_url)

            # prepare dict to pass to UrlCreateSuccess for context data
            self.request.session.update({
                'short_url_hash': url_obj.short_url_hash,
                'raw_password': raw_password
            })
            return super().form_valid(form)


class UrlCreateSuccess(TemplateView):
    """
    View to redirect after successful creation a short url.
    As a GET method in UrlCreate view is actually not idempotent,
    we need to redirect a user to /success/ URI to prevent creation
    of a new record to db if the user accidentally hit the originally
    requested URL one more time.
    """
    template_name = 'short_urls/url_create_success.html'

    def get_context_data(self, **kwargs):
        """
        Extract data from session generated by UrlCreate and UrlCreateByForm views
        """
        context = super().get_context_data(**kwargs)
        context_data = {k: self.request.session.get(k) for k in self.request.session.keys()}
        context.update(context_data)
        return context


class UrlOpen(View):
    """
    Increment click counter and open a short url on a warning page
    """
    def get(self, request, **kwargs):
        short_url_hash = kwargs.get('short_url_hash')
        url_obj = get_object_or_404(Url, short_url_hash=short_url_hash, is_active=True)
        url_obj.clicks_on_short_url = F('clicks_on_short_url') + 1
        url_obj.save()
        return render(
            request, 'short_urls/url_open.html',
            context={'long_url': url_obj.long_url, 'short_url_hash': url_obj.short_url_hash}
        )


class RedirectToLongURL(RedirectView):
    """
    This layer of view was added to count clicks on long URL
    """
    def get(self, request, *args, **kwargs):
        self.url_obj = get_object_or_404(
            Url, short_url_hash=kwargs.get('short_url_hash'), is_active=True
        )
        self.url_obj.clicks_on_long_url = F('clicks_on_long_url') + 1
        self.url_obj.save()
        return super().get(request,*args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return self.url_obj.long_url


class UrlInformation(TemplateView):
    """
    Show short url's information when user has typed command in browser's address bar:
    https://lzy.su/<short_url_identifier>/<command>/<password>
    For example: https://lzy.su/Aq6/i/46754
    Command 'i' in the url means - Information
    """
    template_name = 'short_urls/url_information.html'

    def get(self, request, **kwargs):
        """
        Check permission by password and do appropriate action
        """
        short_url_hash = kwargs.get('short_url_hash')
        url_obj = get_object_or_404(Url, short_url_hash=short_url_hash, is_active=True)

        if check_password(kwargs.get('password'), url_obj.password):
            self.url_obj = url_obj
            return super().get(request, kwargs)
        return render(request, 'short_urls/url_password_error.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'short_url_clicks': self.url_obj.clicks_on_short_url,
            'long_url_clicks': self.url_obj.clicks_on_long_url,
            'url_created': self.url_obj.created,
            'long_url': self.url_obj.long_url
        })
        return context


class UrlDelete(View):
    """
    Delete short url when user has typed command in browser's address bar:
    https://lzy.su/<short_url_identifier>/<command>/<password>
    For example: https://lzy.su/Aq6/d/46754
    Command 'd' in the url means - Delete
    """
    def get(self, request, **kwargs):
        """
        Check permission by password and do appropriate action
        """
        password = kwargs.get('password')
        short_url_hash = kwargs.get('short_url_hash')
        url_obj = get_object_or_404(Url, short_url_hash=short_url_hash)

        if check_password(password, url_obj.password):
            url_obj.is_active = False
            url_obj.save()
            return render(request, 'short_urls/url_delete.html')
        return render(request, 'short_urls/url_password_error.html')
