# Generated by Django 4.0.5 on 2022-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0002_alter_url_pass_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='pass_to_delete',
            field=models.IntegerField(default=0),
        ),
    ]
