# Generated by Django 4.0.5 on 2022-06-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0009_rename_url_url_long_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='click',
            new_name='clicks',
        ),
        migrations.AddField(
            model_name='url',
            name='clicks_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(max_length=2048),
        ),
    ]
