# Generated by Django 3.2 on 2022-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0011_url_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='user_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True),
            preserve_default=False,
        ),
    ]
