# Generated by Django 3.2.14 on 2022-08-09 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0023_forbiddendomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddendomain',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
