# Generated by Django 3.2.14 on 2023-06-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0028_alter_forbiddendomain_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddendomain',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='short_urls.url'),
        ),
    ]
