# Generated by Django 3.2.14 on 2023-06-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0029_forbiddendomain_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forbiddendomain',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='forbidden_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='short_urls.forbiddendomain'),
        ),
    ]
