# Generated by Django 5.0.1 on 2024-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0032_url_is_redirected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='clicks_on_long_url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='is_redirected',
        ),
        migrations.AddField(
            model_name='url',
            name='is_spam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
