name: Deploy by SSH
on: workflow_dispatch

jobs:
  check_django_deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check deploy environment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/lzy.su/app
            python3 manage.py check --deploy



  deploy:
    needs: [check_django_deploy]
    runs-on: ubuntu-24.04
    steps:
      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/lzy.su
            git pull origin docker
            docker compose down
            docker compose up --build -d
