name: Deploy by SSH
on: workflow_dispatch

jobs:
  check_django_deploy:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check deploy environment
        env:
          PIP_CACHE_DIR: /home/gh-actions/.cache/pip
          PATH: /home/gh-actions/.local/bin:$PATH
        run: |
          apt update
          apt install -y sudo
          adduser --disabled-password --gecos "" gh-actions
          usermod -aG sudo gh-actions
          sudo -u gh-actions python3 -m pip install -r ./app/requirements/dev.txt
          sudo -u gh-actions OUTPUT=$(python3 ./app/manage.py check --deploy 2>&1)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "WARNINGS:"; then
            echo "Django deploy warnings found!"
            exit 1
          fi
        shell: bash

  # deploy:
  #   needs: [check_django_deploy]
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Execute remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USER }}
  #         key: ${{ secrets.KEY }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd ~/lzy.su
  #           git pull origin docker
  #           docker compose down
  #           docker compose up --build -d
