name: Deploy by SSH
on: [workflow_dispatch, push]

jobs:
  check_django_deploy:
    runs-on: ubuntu-24.04
    environment:
      name: Production Environment
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Set deploy variables
        # env:
        #   SECRET_KEY: ${{ secrets.PRODUCTION_SECRET_KEY }}
        #   SECRET_ADMIN_URL: ${{ secrets.PRODUCTION_SECRET_ADMIN_URL }}
        #   DEBUG: False
        #   POSTGRES: True
        #   POSTGRES_DB: ${{ secrets.PRODUCTION_POSTGRES_DB }}
        #   POSTGRES_USER: ${{ secrets.PRODUCTION_POSTGRES_USER }}
        #   POSTGRES_PASSWORD: ${{ secrets.PRODUCTION_POSTGRES_PASSWORD }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SECRET_KEY: ${{ secrets.PRODUCTION_SECRET_KEY }}
          envkey_ADMIN_URL: ${{ secrets.PRODUCTION_SECRET_ADMIN_URL }}
          envkey_DEBUG: False
          envkey_POSTGRES: True
          envkey_POSTGRES_DB: ${{ secrets.PRODUCTION_POSTGRES_DB }}
          envkey_POSTGRES_USER: ${{ secrets.PRODUCTION_POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.PRODUCTION_POSTGRES_PASSWORD }}
          file_name: ./app/.env
          
      - name: Check deploy environment
        run: |
          python3 -m pip install -r ./app/requirements/dev.txt
          OUTPUT=$(python3 ./app/manage.py check --deploy --traceback 2>&1)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "WARNINGS:"; then
            echo "Django deploy warnings found!"
            exit 1
          fi
        # shell: bash


  # deploy:
  #   needs: [check_django_deploy]
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Execute remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USER }}
  #         key: ${{ secrets.KEY }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd ~/lzy.su
  #           git pull origin docker
  #           docker compose down
  #           docker compose up --build -d
