name: Django Tests

on:
  workflow_dispatch:
    branches:
      - docker

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r ./app/requirements/dev.txt
      - name: Lint with flake8
        run: flake8 ./app

  testing:
    needs: [linting]
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: database
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r ./app/requirements/dev.txt
      
      - name: Run migrations
        run: python3 ./app/manage.py migrate

      - name: Run tests
        run: python3 ./app/manage.py test short_urls core users
