name: Django Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env_file:
          - ./app/.env
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python3 -m pip install -r lzy.su/app/requrements/dev.txt
      
      - name: Run migrations
        run: python3 ./app/manage.py migrate

      - name: Run tests
        run: python3 ./app/manage.py test